server:
  port: 8080
spring:
  application:
    name: accounts
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/accounts
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
